services:

    ####################################################################################################
    #### FRAMEWORK SPECIFIC
    ####################################################################################################
    api.controller.default:
        class: ApiBundle\Controller\DefaultController
